__include__: [
  './rtdetrv2_hgnetv2_l_6x_coco.yml',
  '../base/rt_deim.yml',
]


output_dir: ./outputs/deim_rtdetrv2_hgnetv2_l_50e_coco

HGNetv2:
  freeze_at: -1     # default 0
  freeze_norm: False   # default True

optimizer:
  type: AdamW
  params: 
    - 
      params: '^(?=.*backbone)(?!.*bn).*$'
      lr: 0.00001
    - 
      params: '^(?=.*(?:norm|bn)).*$'
      weight_decay: 0.

  lr: 0.0002
  betas: [0.9, 0.999]
  weight_decay: 0.0001

# change part
epoches: 50
flat_epoch: 29  # 4 + 50 / 2 
no_aug_epoch: 2

train_dataloader: 
  dataset: 
    transforms:
      policy:
        epoch: [4, 29, 48]   # list 
      
  collate_fn:
    mixup_epochs: [4, 29]
    stop_epoch: 48